# Generated by Django 2.2.14 on 2020-12-26 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que_file', models.FileField(null=True, upload_to='static/question_papers')),
                ('question', models.CharField(max_length=1000)),
                ('que_type', models.CharField(choices=[('help', 'Helping others'), ('com', 'Communicational'), ('org', 'Organizational')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('sa', 'Strongly agree'), ('a', 'Agree'), ('n', 'Neutral'), ('d', 'Disagree'), ('sd', 'Strongly Disagree')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
