# Generated by Django 2.2.14 on 2020-12-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='que_file',
            field=models.FileField(blank=True, null=True, upload_to='static/question_papers'),
        ),
    ]
