# Generated by Django 2.2.14 on 2020-12-26 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_remove_question_que_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='answer',
        ),
        migrations.AddField(
            model_name='question',
            name='option',
            field=models.CharField(choices=[('strongly_agree', 'Strongly agree'), ('agree', 'Agree'), ('neutral', 'Neutral'), ('disagree', 'Disagree'), ('strongly_disagree', 'Strongly Disagree')], default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
