# Generated by Django 2.2.14 on 2020-12-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_auto_20201226_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option',
            field=models.CharField(blank=True, choices=[('strongly_agree', 'Strongly agree'), ('agree', 'Agree'), ('neutral', 'Neutral'), ('disagree', 'Disagree'), ('strongly_disagree', 'Strongly Disagree')], max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
