# Generated by Django 2.2.14 on 2020-12-26 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_auto_20201226_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='option',
            new_name='selected_option',
        ),
    ]
